#cloud-config
ssh_pwauth: no
users:
  - name: netzen
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    lock_passwd: true
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBSDOPWi2De9QKoyrkQn6/zOesiYS4AMEQ9KZyE4oR+Z netzen@MacBook-Pro--netzen.local
write_files:
- content: |
    routes:
      - input:
          plugin: metrics_pull 
          config:
            url: http://localhost:9090/metrics
            format:
              prometheus: {}
        channel:
          channel_ref:
            name: cloud_monitoring
  path: /va/prometheus.yml