version: '3.7'
services:
  catgpt:
    container_name: catgpt
    image: "cr.yandex/crpbccj0cfhnv6t6ocnd/catgpt:latest"
    restart: always
    network_mode: "host"
  unifiedagent:
    container_name: unifiedagent 
    image: "cr.yandex/yc/unified-agent" 
    environment:
      FOLDER_ID: "b1g5tv4fsuuk2l9gvd1p"
    restart: always 
    network_mode: "host" 
    volumes:
      - /ua:/etc/yandex/unified_agent/conf.d
  
