name: Docker Image CI

on: [push]

jobs:
  build_and_push_to_yc:
    name: Push Docker image to Yandex Cloud Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          # this generated key

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpbccj0cfhnv6t6ocnd
          IMAGE_TAG: catgpt:${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$IMAGE_TAG catgpt/.
          docker push cr.yandex/$CR_REGISTRY/$IMAGE_TAG
